# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: プロフィール
    url: /
    weight: 10
  - name: 研究内容
    url: research/
    weight: 20
  - name: 業績・活動
    url: activity/
    weight: 30
  - name: リンク
    url: links/
    weight: 40
